repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: insert-license
        files: \.rs$
        args:
          - --license-filepath
          - scripts/license-header.txt
          - --comment-style
          - //
          - --use-current-year
  - repo: local
    hooks:
      - id: cargo-sort
        name: Check Cargo.toml is sorted
        entry: cargo-sort
        args: ["--workspace"]
        language: rust
        types: [file, toml]
        files: Cargo\.toml
        pass_filenames: false
