version: '2'

services:
  ceresmeta:
    image: ceresmeta-server:latest
    ports:
      - "2379:2379"
    volumes:
      - ./docker/ceresmeta.toml:/etc/ceresmeta/ceresmeta.toml

  ceresdb0:
    image: ceresdb-server:latest
    restart: always
    ports:
      - "8832:8832"
      - "5441:5441"
    volumes:
      - ./docker/ceresdb-cluster-0.toml:/etc/ceresdb/ceresdb.toml
    depends_on:
      - ceresmeta

  ceresdb1:
    image: ceresdb-server:latest
    restart: always
    ports:
      - "8833:8833"
      - "5442:5442"
    volumes:
      - ./docker/ceresdb-cluster-1.toml:/etc/ceresdb/ceresdb.toml
    depends_on:
      - ceresmeta
