# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "benchmarks"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true

[[bin]]
name = "pooled_parser_mem"
path = "src/bin/pooled_parser_mem.rs"

[[bin]]
name = "prost_parser_mem"
path = "src/bin/prost_parser_mem.rs"

[[bin]]
name = "rust_protobuf_parser_mem"
path = "src/bin/rust_protobuf_parser_mem.rs"

[[bin]]
name = "quick_protobuf_parser_mem"
path = "src/bin/quick_protobuf_parser_mem.rs"

[[bin]]
name = "pool_stats"
path = "src/bin/pool_stats.rs"

[features]
unsafe-split = ["remote_write/unsafe-split"]

[dependencies]
bytes = { workspace = true }
columnar_storage = { workspace = true }
common = { workspace = true }
deadpool = { workspace = true }
pb_types = { workspace = true }
prost = { workspace = true }
protobuf = "3.7"
quick-protobuf = "0.8"
remote_write = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tikv-jemalloc-ctl = "0.5"
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[build-dependencies]
protobuf-codegen = "3.7"

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench"
harness = false
