[package]
name = "analytic_engine"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdb@service.alipay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test = ["tempfile"]

[dependencies]
# In alphabetical order
arc-swap = "1.4.0"
arena = { path = "../components/arena" }
arrow_deps = { path = "../arrow_deps" }
async-trait = "0.1.53"
base64 = "0.13"
common_types = { path = "../common_types" }
common_util = { path = "../common_util"}
futures = "0.3"
lazy_static = "1.4.0"
log = "0.4"
iox_object_store = { path = "../components/iox_object_store" }
parquet = { path = "../components/parquet" }
prometheus = "0.12"
proto = { path = "../proto" }
protobuf = "2.20"
serde = "1.0"
serde_derive = "1.0"
skiplist = { path = "../components/skiplist" }
smallvec = "1.6"
snafu = { version = "0.6.10", features = ["backtraces"] }
table_engine = { path = "../table_engine" }
tokio = { version = "1.0", features = ["sync", "time"] }
wal = { path = "../wal" }
tempfile = { version = "3.1.0", optional = true }

[dev-dependencies]
common_types = { path = "../common_types", features = ["test"] }
common_util = { path = "../common_util", features = ["test"] }
env_logger = "0.6"
tempfile = "3.1.0"
