[package]
name = "df_operator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow_deps = { path = "../arrow_deps" }
base64 = "0.13"
bincode = "1.3"
chrono = "0.4"
common_types = { path = "../common_types" }
common_util = { path = "../common_util" }
hyperloglog = { git = "https://github.com/jedisct1/rust-hyperloglog.git", rev = "ed1b9b915072ba90c6b93fbfbba30c03215ba682", features = ["with_serde"] }
smallvec = "1.6"
snafu = { version ="0.6.10", features = ["backtraces"]}
