[package]
name = "df_operator"
version = "0.1.0"

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow_deps = { path = "../arrow_deps" }
base64 = { workspace = true }
bincode = "1.3"
chrono = "0.4"
common_types = { workspace = true }
common_util = { workspace = true }
hyperloglog = { git = "https://github.com/jedisct1/rust-hyperloglog.git", rev = "ed1b9b915072ba90c6b93fbfbba30c03215ba682", features = ["with_serde"] }
smallvec = { workspace = true }
snafu = { workspace = true }
