[package]
name = "system_catalog"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# In alphabetical order
arrow_deps = { path = "../arrow_deps" }
async-trait = "0.1.53"
catalog = { path = "../catalog" }
common_types = { path = "../common_types" }
common_util = { path = "../common_util" }
futures = "0.3"
log = "0.4"
proto = { path = "../proto" }
protobuf = "2.20"
snafu = { version = "0.6.10", features = ["backtraces"] }
table_engine = { path = "../table_engine" }
tokio = { version = "1.0", features = ["sync"] }
