[package]
name = "catalog"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdb@service.alipay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies, in alphabetical order
async-trait = "0.1.53"
snafu = { version ="0.6.10", features = ["backtraces"]}
common_types = { path = "../common_types" }
common_util = { path = "../common_util" }
table_engine = { path = "../table_engine" }
