[package]
name = "parquet"
version = "0.1.0"

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow_deps = { path = "../../arrow_deps" }
lru = "0.7.0"
parquet-format = "4.0.0"
thrift = "0.13"
bytes = { workspace = true }