[node]
addr = "ceresdb1"

[server]
bind_addr = "0.0.0.0"
http_port = 5442
grpc_port = 8833
mysql_port = 3307
log_level = "info"
deploy_mode = "Cluster"

[server.forward]
enable = true

[analytic.storage]
mem_cache_capacity = '1G'
mem_cache_partition_bits = 0

[analytic.storage.object_store]
type = "Local"
data_dir = "/tmp/ceresdb0"

[analytic.wal_storage]
type = "RocksDB"
data_dir = "/tmp/ceresdb0"

[cluster_deployment]
mode = "WithMeta"
cmd_channel_buffer_size = 10

[cluster_deployment.meta_client]
# Only support "defaultCluster" currently.
cluster_name = "defaultCluster"
meta_addr = "http://ceresmeta:2379"
lease = "10s"
timeout = "5s"

[limiter]
write_block_list = ['mytable1']
read_block_list = ['mytable1']
