[package]
name = "arrow_ext"
[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies.uncover]
git = "https://github.com/matklad/uncover.git"
rev = "1d0770d997e29731b287e9e11e4ffbbea5f456da"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { workspace = true }

