[package]
name = "catalog_impls"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies, in alphabetical order
async-trait = { workspace = true }
catalog = { workspace = true }
common_types = { workspace = true }
common_util = { workspace = true }
log = { workspace = true }
meta_client = { workspace = true }
snafu = { workspace = true }
system_catalog = { workspace = true }
table_engine = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
analytic_engine = { workspace = true, features = ["test"] }
server = { workspace = true }
