[package]
name = "table_engine"
[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# In alphabetical order
arrow = { workspace = true }
async-trait = { workspace = true }
common_types = { workspace = true }
common_util = { workspace = true }
datafusion = { workspace = true }
datafusion-expr = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
parquet = { workspace = true }
parquet_ext = { workspace = true }
prost = { workspace = true }
proto = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
smallvec = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true }
