[package]
name = "arrow_deps"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "15.0.0"
parquet = "15.0.0"

[dependencies.uncover]
git = "https://github.com/matklad/uncover.git"
rev = "1d0770d997e29731b287e9e11e4ffbbea5f456da"

[dependencies.datafusion]
git = "https://github.com/waynexia/arrow-datafusion.git"
rev = "d8184e71589e95b27db0e2c0ce0a8c51a6564c7a"

[dependencies.datafusion-expr]
git = "https://github.com/waynexia/arrow-datafusion.git"
rev = "d8184e71589e95b27db0e2c0ce0a8c51a6564c7a"
