[package]
name = "ceresdbproto_deps"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.ceresdbproto]
git = "https://github.com/ShiKaiWi/ceresdbproto.git"
rev = "d50af739749129b81da52af034902e34a8dbd04e"