[package]
name = "meta_client"
[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
ceresdbproto = { workspace = true }
common_types = { workspace = true }
common_util = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
reqwest = "0.11.13"
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
url = "2.2"
