[package]
name = "table_kv"
version = "0.1.0"

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_util = { path = "../../common_util" }
log = { workspace = true }
obkv-table-client-rs = { git = "https://github.com/oceanbase/obkv-table-client-rs.git", rev = "318907f35de51404c05180c65440c9516fd1e10f" }
serde = { workspace = true }
serde_derive = { workspace = true }
snafu = { workspace = true }

[dev-dependencies]
rand = "0.7"
