[package]
name = "skiplist"
authors = ["Jay Lee <busyjaylee@gmail.com>", "CeresDB Authors <ceresdbservice@gmail.com>"]


[package.version]
workspace = true

[package.edition]
workspace = true
[dependencies]
arena = { workspace = true }
bytes = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
yatp = { git = "https://github.com/tikv/yatp.git", rev = "4b71f8abd86890f0d1e95778c2b6bf5a9ee4c502" }
# [target.'cfg(not(target_env = "msvc"))'.dev-dependencies]
# tikv-jemallocator = "0.4.0"

[[bench]]
name = "bench"
harness = false
