bind_addr = "0.0.0.0"
http_port = 5440
grpc_port = 8831
log_level = "info"
enable_cluster = true

[query]
read_parallelism = 8

[analytic]
wal_path = "/tmp/ceresdb"
sst_data_cache_cap = 10000
sst_meta_cache_cap = 10000

[analytic.storage]
type = "Cache"
cache_opts = { max_cache_size = 10000000 }

[analytic.storage.local_store]
type = "Local"
data_path = "/tmp/ceresdb"

[analytic.storage.remote_store]
type = "Aliyun"
key_id = "key_id"
key_secret = "key_secret"
endpoint = "endpoint"
bucket = "bucket"

[[meta_client.cluster_view.schema_shards]]
schema = 'public'

[[meta_client.cluster_view.schema_shards.shard_views]]
shard_id = 0

[meta_client.cluster_view.schema_shards.shard_views.node]
addr = "127.0.0.1"
port = 8831
