bind_addr = "127.0.0.1"
http_port = 5440
grpc_port = 8831
log_level = "info"

[analytic.storage]
type = "Local"
data_path = "/tmp/ceresdb"

[analytic]
wal_path = "/tmp/ceresdb"
sst_data_cache_cap = 10000
sst_meta_cache_cap = 10000

[[static_route.topology.schema_shards]]
schema = 'public'
auto_create_tables = true

[[static_route.topology.schema_shards.shard_views]]
shard_id = 0

[static_route.topology.schema_shards.shard_views.endpoint]
addr = "127.0.0.1"
port = 8831