[node]
addr = "ceresdb0"

[server]
bind_addr = "127.0.0.1"
http_port = 5440
grpc_port = 8831

[query_engine]
read_parallelism = 8

[analytic.wal]
type = "RocksDB"
data_dir = "/tmp/ceresdb"

[analytic.storage]
mem_cache_capacity = '1G'
mem_cache_partition_bits = 0
disk_cache_dir = "/tmp/ceresdb"
disk_cache_capacity = '2G'
disk_cache_page_size = '1M'

[analytic.storage.object_store]
type = "Local"
data_dir = "/tmp/ceresdb"
