[package]
name = "benchmarks"
version = "0.1.0"

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arena = { workspace = true }
arrow2 = { version = "0.12.0", features = [ "io_parquet" ] }
arrow_deps = { path = "../arrow_deps" }
analytic_engine = { workspace = true }
base64 = { workspace = true }
clap = "2.0"
common_types = { workspace = true }
common_util = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
object_store = { workspace = true }
parquet = { path = "../components/parquet"}
rand = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
snafu = { workspace = true }
table_engine = { workspace = true }
table_kv = { workspace = true }
tokio = { workspace = true }
wal = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench"
harness = false

[[bin]]
name = "sst-tools"
