[package]
name = "sql"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test = []

[dependencies]
# In alphabetical order
arrow_deps = { path = "../arrow_deps" }
catalog = { workspace = true }
ceresdbproto = { workspace = true }
common_types = { workspace = true }
common_util = { workspace = true }
df_operator = { workspace = true }
hashbrown = { version = "0.12", features = ["raw"] }
log = { workspace = true }
paste = { workspace = true }
snafu = { workspace = true }
sqlparser = "0.23.0"
table_engine = { workspace = true }
regex = "1"

[dev-dependencies]
common_types = { workspace = true, features = ["test"] }
tokio = { workspace = true }
