[package]
name = "sql"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[features]
test = []

[dependencies]
# In alphabetical order
arrow = { workspace = true }
async-trait = { workspace = true }
catalog = { workspace = true }
ceresdbproto = { workspace = true }
cluster = { workspace = true }
common_types = { workspace = true }
common_util = { workspace = true }
datafusion = { workspace = true }
datafusion-expr = { workspace = true }
datafusion-proto = { workspace = true }
df_operator = { workspace = true }
hashbrown = { version = "0.12", features = ["raw"] }
log = { workspace = true }
paste = { workspace = true }
regex = "1"
snafu = { workspace = true }
sqlparser = { workspace = true }
table_engine = { workspace = true }
influxdb_influxql_parser = {git = "https://github.com/Rachelint/influxdb_iox.git", branch = "influxql-parser"}
regex-syntax = "0.6.28"

[dev-dependencies]
common_types = { workspace = true, features = ["test"] }
tokio = { workspace = true }
