name: Test Docker image build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'docker/**'
      - 'docs/minimal.toml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'docker/**'
      - 'docs/minimal.toml'

env:
  CERESDB_ADDR: 127.0.0.1
  CERESDB_PORT: 5440
  IMAGE_NAME: ceresdb-server:latest
  SERVER_NAME: standalone-server

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Docker image
        run: docker build -t ${IMAGE_NAME} .
      - name: Test the Built Image
        run: |
          docker run --name ${SERVER_NAME} -p ${CERESDB_ADDR}:${CERESDB_PORT}:${CERESDB_PORT} -d ${IMAGE_NAME}
          sleep 10
          bash ./docker/basic.sh
          docker rm -f ${SERVER_NAME}
      - name: Test the Built Image With Config
        run: |
          docker run --name ${SERVER_NAME} -p ${CERESDB_ADDR}:${CERESDB_PORT}:${CERESDB_PORT} \
            -v `pwd`/docs/minimal.toml:/etc/ceresdb/ceresdb.toml -d ${IMAGE_NAME}
          sleep 10
          bash ./docker/basic.sh
          docker rm -f ${SERVER_NAME}
