name: Build Docker Image without Pushing

on:
  push:
    paths:
      - '.github/workflows/docker-build-image.yml'
      - 'Dockerfile'
      - 'docker/**'

env:
  CERESDB_ADDR: 127.0.0.1
  CERESDB_PORT: 5440

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t ceresdb-server .
      - name: Test the Built Image
        run: >-
          docker run -p ${CERESDB_ADDR}:${CERESDB_PORT}:${CERESDB_PORT} -d ceresdb-server &&
          bash ./tests/basic.sh
