name: TSBS Benchmark

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'scrits/run-tsbs.sh'
    paths-ignore:
  schedule:
    - cron: '2 0 * * *'

jobs:
  run-tsbs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Release Disk Quota
        run: |
          sudo rm -rf /usr/local/lib/android # release about 10 GB
          sudo rm -rf /usr/share/dotnet # release about 20GB
      - name: Cache Rust Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./target
          key: release-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            release-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-
            release-${{ runner.os }}-
            release-${{ runner.os }}
      - name: Ensure Disk Quota
        run: |
          make ensure-disk-quota
      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install --yes protobuf-compiler
      - name: Build server
        run: |
          make build
      - name: Run TSBS
        run: |
          ./scripts/run-tsbs.sh
          echo "NOW=$(TZ=':Asia/Shanghai' date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_ENV
      - name: Update Summary
        run: |
          cat tsbs/result.md >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v3
        with:
          name: bench-${{ env.NOW }}
          path: |
            logs/**
            tsbs/result.md
